# Snakemake configuration

input:
    "/rds/user/aa2369/hpc-work/scripts/snakemake/virsearch/test/input" # path to input directory with .fa files

output:
    "/rds/user/aa2369/hpc-work/scripts/snakemake/virsearch/test/output" # path to output directory

database: 
    "/rds/project/rds-aFEMMKDjWlo/rfs_data/databases/virsearch" # path to database folder
