# Snakemake configuration

input:
    "/rds/project/rds-aFEMMKDjWlo/rarora/assemblies" # path to input directory with .fa files

output:
    "/rds/project/rds-aFEMMKDjWlo/rarora/viruses" # path to output directory

usearch_binary:
    "tools/usearch" # path to usearch binary

database: 
    "/rds/project/rds-aFEMMKDjWlo/rfs_data/databases/virsearch" # path to database folder
